// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entity_Framework_Exercise.Migrations
{
    [DbContext(typeof(LibraryDbContext))]
    partial class LibraryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RackId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RackId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RackId = 1,
                            Status = 0,
                            Title = "Advanced C#"
                        },
                        new
                        {
                            Id = 2,
                            RackId = 1,
                            Status = 0,
                            Title = "Intermediate C#"
                        },
                        new
                        {
                            Id = 3,
                            RackId = 1,
                            Status = 0,
                            Title = "Beginner C#"
                        });
                });

            modelBuilder.Entity("Models.Rack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Racks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Self-Improvement"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fiction"
                        });
                });

            modelBuilder.Entity("Models.Book", b =>
                {
                    b.HasOne("Models.Rack", "Rack")
                        .WithMany("Books")
                        .HasForeignKey("RackId");

                    b.Navigation("Rack");
                });

            modelBuilder.Entity("Models.Rack", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
