classDiagram
direction TB

class ColorType {
    Black
    White
}
<<enumeration>> ColorType

class PieceState {
    Active
    Captured
    Promoted
}
<<enumeration>> PieceState

class GameState {
    Init
    IntendingMove
    MakingMove
    CheckmateBlackWin
    CheckmateWhiteWin
    Stalemate
    Resignation
}
<<enumeration>> GameState

class PawnPromotionType {
    Rook
    Bishop
    Knight
    Queen
}
<<enumeration>> PawnPromotionType

class Point {
    +int X
    +int Y
}
<<struct>> Point

class IBoard {
    +GetSquare(Point coordinate) :: Square
    +GetKing(ColorType side) :: Piece
    +Traverse(List<.Point> directions, bool isMovementRepeat) :: List<.Square> traverseResult
    +ResetBoard() :: void
}
<<interface>> IBoard

class IPiece {
    +GetMovementBehavior(out List<.Point> directions, out bool isMovementRepeat)
}
<<interface>> IPiece

class ISpecialPieceMovement {
    +GetSpecialMovement(out Point direction)
}
<<interface>> ISpecialPieceMovement

class GameController {
    +DateTime dateTime
    +List<.Dictionary<.ColorType, int>> players
    +Board Board
    +List<.Piece> pieces
    +GameState State
    -int _currentPlayerIndex
    -Square? _intendedSquareSource
    +Utility utility
    +List<.Square>? CurrentLegalMoves
    +GameController()
    +InitGame() :: void
    +NextTurn() :: void
    +IntendMove(Square sourceSquare) :: void
    +GetLegalMoves(Square sourceSquare) :: List<.Square>
    +CancelMove() :: void
    +MakeMove(Square destinationSquare) :: bool
    +Action? OnMoveDone
    +HandleMoveDone() :: void
    +Action<.Piece>? OnCapturePiece
    +HandleCapturePiece(Piece capturedPiece) :: void
    +Action<.Rook>? OnCastling
    +HandleCastling(Rook rook) :: void
    +Action<.Pawn>? OnEnPassant
    +HandleEnPassant(Pawn capturedPawn) :: void
    +Action<.Pawn>? OnPawnPromotion
    +HandlePawnPromotion(Pawn pawn)
    +Action? OnCheckmate
    +Action? OnResign
    +Action? OnStalemate
    +HandleEndgame() :: void
}

class Board {
    +Square[][] squares
    +Board()
}

class Square {
    +Point coordinate
    +Piece? piece
    +Square(uint file, uint rank)
}

class Piece {
    +ColorType Color : readonly
    +PieceState State
    +PieceType Type
    +List<.Point> Directions
    +bool isMovementRepeat
    +bool hasSpecialMove
    +uint InitialPositionX : readonly
    +uint InitialPositionY : readonly
    +Piece(ColorType side) : void
}

class King {
    +List<.Point> castlingCoordinates
}

class Pawn {
    +Point EnPassantDirection
    -bool _isPromoted
    -PawnPromotionType _promotionType
    +bool PromotePawn(PawnPromotionType targetPromotion) :: void
}

class Queen
class Knight
class Rook
class Bishop

Board *-- Square
GameController *-- Piece
GameController *-- Board
GameController o-- GameState
IBoard <|-- Board
IPiece <|.. Piece
ISpecialPieceMovement <|.. Pawn
ISpecialPieceMovement <|.. King
Pawn o-- PawnPromotionType
Piece o-- PieceState
Piece o-- ColorType
Piece o-- Point
Piece <|-- King
Piece <|-- Pawn
Piece <|-- Queen
Piece <|-- Rook
Piece <|-- Bishop
Piece <|-- Knight
Square o-- Point
Square -- Piece
Square o-- Point
